
class CustomerListModel {
    int? customerId;
    String? name;
    String? joinDate;
    String? email;
    int? mobile;
    String? streetNo;
    String? villaNumber;
    String? roomNo;
    String? refNo;
    String? cusCode;
    String? area;
    String? hotel;
    int? discount;
    String? acType;
    String? deliveryType;
    int? openingBalance;
    int? wallet;
    int? cusPaidAmount;
    int? cusBalance;
    String? fragrance;
    String? zone;
    String? packingType;
    String? starch;
    bool? autoGenerated;
    bool? trash;

    CustomerListModel({this.customerId, this.name, this.joinDate, this.email, this.mobile, this.streetNo, this.villaNumber, this.roomNo, this.refNo, this.cusCode, this.area, this.hotel, this.discount, this.acType, this.deliveryType, this.openingBalance, this.wallet, this.cusPaidAmount, this.cusBalance, this.fragrance, this.zone, this.packingType, this.starch, this.autoGenerated, this.trash});

    CustomerListModel.fromJson(Map<String, dynamic> json) {
        if(json["customerId"] is num) {
            customerId = (json["customerId"] as num).toInt();
        }
        if(json["name"] is String) {
            name = json["name"];
        }
        if(json["joinDate"] is String) {
            joinDate = json["joinDate"];
        }
        if(json["email"] is String) {
            email = json["email"];
        }
        if(json["mobile"] is num) {
            mobile = (json["mobile"] as num).toInt();
        }
        if(json["streetNo"] is String) {
            streetNo = json["streetNo"];
        }
        if(json["villaNumber"] is String) {
            villaNumber = json["villaNumber"];
        }
        if(json["roomNo"] is String) {
            roomNo = json["roomNo"];
        }
        if(json["refNo"] is String) {
            refNo = json["refNo"];
        }
        if(json["cusCode"] is String) {
            cusCode = json["cusCode"];
        }
        if(json["area"] is String) {
            area = json["area"];
        }
        if(json["hotel"] is String) {
            hotel = json["hotel"];
        }
        if(json["discount"] is num) {
            discount = (json["discount"] as num).toInt();
        }
        if(json["acType"] is String) {
            acType = json["acType"];
        }
        if(json["deliveryType"] is String) {
            deliveryType = json["deliveryType"];
        }
        if(json["openingBalance"] is num) {
            openingBalance = (json["openingBalance"] as num).toInt();
        }
        if(json["wallet"] is num) {
            wallet = (json["wallet"] as num).toInt();
        }
        if(json["cusPaidAmount"] is num) {
            cusPaidAmount = (json["cusPaidAmount"] as num).toInt();
        }
        if(json["cusBalance"] is num) {
            cusBalance = (json["cusBalance"] as num).toInt();
        }
        if(json["fragrance"] is String) {
            fragrance = json["fragrance"];
        }
        if(json["zone"] is String) {
            zone = json["zone"];
        }
        if(json["packingType"] is String) {
            packingType = json["packingType"];
        }
        if(json["starch"] is String) {
            starch = json["starch"];
        }
        if(json["auto_generated"] is bool) {
            autoGenerated = json["auto_generated"];
        }
        if(json["trash"] is bool) {
            trash = json["trash"];
        }
    }

    static List<CustomerListModel> fromList(List<Map<String, dynamic>> list) {
        return list.map(CustomerListModel.fromJson).toList();
    }

    Map<String, dynamic> toJson() {
        final Map<String, dynamic> _data = <String, dynamic>{};
        _data["customerId"] = customerId;
        _data["name"] = name;
        _data["joinDate"] = joinDate;
        _data["email"] = email;
        _data["mobile"] = mobile;
        _data["streetNo"] = streetNo;
        _data["villaNumber"] = villaNumber;
        _data["roomNo"] = roomNo;
        _data["refNo"] = refNo;
        _data["cusCode"] = cusCode;
        _data["area"] = area;
        _data["hotel"] = hotel;
        _data["discount"] = discount;
        _data["acType"] = acType;
        _data["deliveryType"] = deliveryType;
        _data["openingBalance"] = openingBalance;
        _data["wallet"] = wallet;
        _data["cusPaidAmount"] = cusPaidAmount;
        _data["cusBalance"] = cusBalance;
        _data["fragrance"] = fragrance;
        _data["zone"] = zone;
        _data["packingType"] = packingType;
        _data["starch"] = starch;
        _data["auto_generated"] = autoGenerated;
        _data["trash"] = trash;
        return _data;
    }

    CustomerListModel copyWith({
        int? customerId,
        String? name,
        String? joinDate,
        String? email,
        int? mobile,
        String? streetNo,
        String? villaNumber,
        String? roomNo,
        String? refNo,
        String? cusCode,
        String? area,
        String? hotel,
        int? discount,
        String? acType,
        String? deliveryType,
        int? openingBalance,
        int? wallet,
        int? cusPaidAmount,
        int? cusBalance,
        String? fragrance,
        String? zone,
        String? packingType,
        String? starch,
        bool? autoGenerated,
        bool? trash,
    }) => CustomerListModel(
        customerId: customerId ?? this.customerId,
        name: name ?? this.name,
        joinDate: joinDate ?? this.joinDate,
        email: email ?? this.email,
        mobile: mobile ?? this.mobile,
        streetNo: streetNo ?? this.streetNo,
        villaNumber: villaNumber ?? this.villaNumber,
        roomNo: roomNo ?? this.roomNo,
        refNo: refNo ?? this.refNo,
        cusCode: cusCode ?? this.cusCode,
        area: area ?? this.area,
        hotel: hotel ?? this.hotel,
        discount: discount ?? this.discount,
        acType: acType ?? this.acType,
        deliveryType: deliveryType ?? this.deliveryType,
        openingBalance: openingBalance ?? this.openingBalance,
        wallet: wallet ?? this.wallet,
        cusPaidAmount: cusPaidAmount ?? this.cusPaidAmount,
        cusBalance: cusBalance ?? this.cusBalance,
        fragrance: fragrance ?? this.fragrance,
        zone: zone ?? this.zone,
        packingType: packingType ?? this.packingType,
        starch: starch ?? this.starch,
        autoGenerated: autoGenerated ?? this.autoGenerated,
        trash: trash ?? this.trash,
    );
}