// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGB4auPtGjteIqElCJMKH1nEQt3-Jno8',
    appId: '1:197388954178:web:23dfdd17172e2c7fbb9bdb',
    messagingSenderId: '197388954178',
    projectId: 'syswash-69645',
    authDomain: 'syswash-69645.firebaseapp.com',
    storageBucket: 'syswash-69645.firebasestorage.app',
    measurementId: 'G-XRVE7SSWJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFwzH_ahcpiT9VYtXj8yIx0GVqwhiQwI',
    appId: '1:197388954178:android:77e927b9b7314e17bb9bdb',
    messagingSenderId: '197388954178',
    projectId: 'syswash-69645',
    storageBucket: 'syswash-69645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCj18XfSRVgkkQ6eEchak2osaMeLWG3X8',
    appId: '1:197388954178:ios:7e0c7bf2180df266bb9bdb',
    messagingSenderId: '197388954178',
    projectId: 'syswash-69645',
    storageBucket: 'syswash-69645.firebasestorage.app',
    iosBundleId: 'com.pupa.syswash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCj18XfSRVgkkQ6eEchak2osaMeLWG3X8',
    appId: '1:197388954178:ios:7e0c7bf2180df266bb9bdb',
    messagingSenderId: '197388954178',
    projectId: 'syswash-69645',
    storageBucket: 'syswash-69645.firebasestorage.app',
    iosBundleId: 'com.pupa.syswash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqvqVFAuhZFJeiihxescRYOd8McNnylDM',
    appId: '1:197388954178:web:6b60d6910f551186bb9bdb',
    messagingSenderId: '197388954178',
    projectId: 'syswash-69645',
    authDomain: 'syswash-69645.firebaseapp.com',
    storageBucket: 'syswash-69645.firebasestorage.app',
    measurementId: 'G-80CVN18NX9',
  );
}
